const akaneko = require('akaneko');

module.exports = [
	akaneko.nsfw.ass(),
	akaneko.nsfw.bdsm(),
	akaneko.nsfw.blowjob(),
	akaneko.nsfw.cum(),
	akaneko.nsfw.doujin(),
	akaneko.nsfw.feet(),
	akaneko.nsfw.femdom(),
	akaneko.nsfw.foxgirl(),
	akaneko.nsfw.gifs(),
	akaneko.nsfw.glasses(),
	akaneko.nsfw.hentai(),
	akaneko.nsfw.netorare(),
	akaneko.nsfw.maid(),
	akaneko.nsfw.masturbation(),
	akaneko.nsfw.mobileWallpapers(),
	akaneko.nsfw.netorare(),
	akaneko.nsfw.orgy(),
	akaneko.nsfw.panties(),
	akaneko.nsfw.pussy(),
	akaneko.nsfw.school(),
	akaneko.nsfw.succubus(),
	akaneko.nsfw.tentacles(),
	akaneko.nsfw.thighs(),
	akaneko.nsfw.uniform(),
	akaneko.nsfw.wallpapers(),
	akaneko.nsfw.yuri(),
	akaneko.nsfw.zettaiRyouiki(),
];