const akaneko = require('akaneko');

module.exports = [
	{ image: akaneko.nsfw.ass(), text: 'Literally porn' },
	{ image: akaneko.nsfw.bdsm(), text: 'Literally porn' },
	{ image: akaneko.nsfw.blowjob(), text: 'Literally porn' },
	{ image: akaneko.nsfw.cum(), text: 'Literally porn' },
	{ image: akaneko.nsfw.doujin(), text: 'Literally porn' },
	{ image: akaneko.nsfw.feet(), text: 'Literally porn' },
	{ image: akaneko.nsfw.femdom(), text: 'Literally porn' },
	{ image: akaneko.nsfw.foxgirl(), text: 'Literally porn' },
	{ image: akaneko.nsfw.gifs(), text: 'Literally porn' },
	{ image: akaneko.nsfw.glasses(), text: 'Literally porn' },
	{ image: akaneko.nsfw.hentai(), text: 'Literally porn' },
	{ image: akaneko.nsfw.netorare(), text: 'Literally porn' },
	{ image: akaneko.nsfw.maid(), text: 'Literally porn' },
	{ image: akaneko.nsfw.masturbation(), text: 'Literally porn' },
	{ image: akaneko.nsfw.mobileWallpapers(), text: 'Literally porn' },
	{ image: akaneko.nsfw.orgy(), text: 'Literally porn' },
	{ image: akaneko.nsfw.panties(), text: 'Literally porn' },
	{ image: akaneko.nsfw.pussy(), text: 'Literally porn' },
	{ image: akaneko.nsfw.school(), text: 'Literally porn' },
	{ image: akaneko.nsfw.succubus(), text: 'Literally porn' },
	{ image: akaneko.nsfw.tentacles(), text: 'Literally porn' },
	{ image: akaneko.nsfw.thighs(), text: 'Literally porn' },
	{ image: akaneko.nsfw.uniform(), text: 'Literally porn' },
	{ image: akaneko.nsfw.wallpapers(), text: 'Literally porn' },
	{ image: akaneko.nsfw.yuri(), text: 'Literally porn' },
	{ image: akaneko.nsfw.zettaiRyouiki(), text: 'Literally porn' },
];