const akaneko = require('akaneko');
const ansfw = akaneko.nsfw;

const hentaiAkanekoPorn = [
	ansfw.ass(),
	ansfw.bdsm(),
	ansfw.blowjob(),
	ansfw.cum(),
	ansfw.doujin(),
	ansfw.feet(),
	ansfw.femdom(),
	ansfw.foxgirl(),
	ansfw.gifs(),
	ansfw.glasses(),
	ansfw.hentai(),
	ansfw.netorare(),
	ansfw.maid(),
	ansfw.masturbation(),
	ansfw.mobileWallpapers(),
	ansfw.orgy(),
	ansfw.panties(),
	ansfw.pussy(),
	ansfw.school(),
	ansfw.succubus(),
	ansfw.tentacles(),
	ansfw.thighs(),
	ansfw.uniform(),
	ansfw.wallpapers(),
	ansfw.yuri(),
	ansfw.zettaiRyouiki(),
];

const hentaiRedditPorn = [
	'hentai',
	'yuri',
	'Tomboy_Hentai',
	'Masturbation_Hentai',
	'rule34',
	'HENTAI_GIF',
	'catgirlhentai',
	'FlatChestHentai',
	'Nekomimi',
	'YuriHentai',
	'hentaifemdom',
];

const irlPorn = [
	'gonewild',
	'BiggerThanYouThought',
	'bigtiddygothgf',
	'BonerMaterial',
	'Boobies',
	'Bottomless',
	'cumshots',
	'cumsluts',
	'dildo',
	'flatchests',
	'GirlsGW',
	'GirlsShowering',
	'Gonewild18',
	'LegalTeens',
	'Lesbians',
	'MasturbationGoneWild',
	'nsfw',
	'Nudes',
	'porn',
	'pussy',
	'scissoring',
	'Slut',
];

module.exports = { hentaiAkanekoPorn, hentaiRedditPorn, irlPorn };